### PR TITLE
add email template

### PR DESCRIPTION
**Pull request by pnzrr**

### CODE REVIEW

**Comment by pnzrr** [comment]
https://github.com/p2-inc/phasetwo-docs/pull/141

**Review by xgp — APPROVED** [review]

**Comment by xgp** [comment]
Actually, samples/examples should probably live in the `keycloak-theme-template` repo with the example login css. This might be confusing as it's the extension that runs the `Attributes` theme

**Comment by pnzrr** [comment]
Moved to here
https://github.com/p2-inc/keycloak-theme-template/pull/4

**Comment by pnzrr** [comment]
I only moved the email template. Let me know if you meant ALL samples

**Comment by pnzrr** [comment]
Email templates in `mustache` are updated

**Review by xgp — APPROVED** [review]

**Comment by xgp** [comment]
@pnzrr We missed https://github.com/p2-inc/keycloak-themes/blob/main/src/main/resources/theme/mustache/email/html/magic-link-continuation-email.mustache

**Pull request merged**
